# lock if sleep
general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
	before_sleep_cmd = hyprlock	# lock before suspend.
	after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display
}

listener {
    timeout = 180                                # 3min.
    on-timeout = light -O && light -S 10         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = light -I                 # monitor backlight restore.
}

listener {
    timeout = 300                                 # 5min
    on-timeout = hyprctl dispatch dpms off                            # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on          # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 900                                 # 15min
    on-timeout = hyprlock           # lock screen when timeout has passed
}

listener {
    timeout = 3600                                # 3hr
    on-timeout = systemctl hibernate              # suspend pc
}

